# Generated by Django 3.0.6 on 2020-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200605_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
