# Generated by Django 3.0.6 on 2020-06-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200605_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiods',
            name='tz',
        ),
        migrations.RemoveField(
            model_name='activityperiods',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
